name: Create Frontend Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:

jobs:
  build_chat:
    name: Push Chat Image
    runs-on: blacksmith-staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/chat
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          # platforms: linux/amd64,linux/arm64
          file: frontends/chat/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  build_search:
    name: Push Search Image
    runs-on: blacksmith-staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/search
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          # platforms: linux/amd64,linux/arm64
          file: frontends/search/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  build_dashboard:
    name: Push Dashboard Image
    runs-on: blacksmith-staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/dashboard
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          # platforms: linux/amd64,linux/arm64
          file: frontends/dashboard/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  build_analytics_site:
    name: Push Analytics Image
    runs-on: blacksmith-staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/analytics-site
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          # platforms: linux/amd64,linux/arm64
          file: frontends/analytics/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true
