name: Create Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
    paths:
      - "server/**"
      - ".github/workflows/**"

jobs:
  build_server:
    name: Push No OCR image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/server
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  ingest_worker:
    name: Push Ingest image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/ingest
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.ingestion-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  delete_worker:
    name: Push Delete worker
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/delete_worker
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.delete-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  file_worker:
    name: Push File Worker image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/file_worker
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.file-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  group_worker:
    name: Push Group worker
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/group_worker
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.group-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  sync_qdrant:
    name: Push Sync Qdrant script
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/sync_qdrant
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.sync-qdrant
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  queue_bm25:
    name: Push Queue BM25 Script
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/queue-bm25-migration
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.queue-bm25
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true

  reindex-worker:
    name: Push Reindex Worker
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204]
        platform: [linux/amd64]
        exclude:
          - runner: blacksmith-staging-4vcpu-ubuntu-2204
            platform: linux/arm64
          - runner: blacksmith-staging-4vcpu-ubuntu-2204-arm
            platform: linux/amd64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            blacksmithcihello/reindex-worker
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@master
        with:
          platforms: ${{ matrix.platform }}
          context: server/
          file: ./server/Dockerfile.reindex-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          nofallback: true
